# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Install dependencies for Playwright (optional heavy)
RUN apt-get update && apt-get install -y wget gnupg libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxkbcommon0 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libgtk-3-0 libasound2 libxshmfence1 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy project files
COPY pyproject.toml setup.cfg* ./
COPY src ./src

# Install project
RUN pip install --no-cache-dir . && python -m playwright install --with-deps

ENTRYPOINT ["google-news-trends-mcp"]
