name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  pypi:
    name: Publish to PyPI & Create GitHub Release
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
      - run: uv build

      - name: Smoke test (wheel)
        run: uv run --isolated --no-project -p 3.13 --with dist/*.whl -m pytest -k test_smoke

      - name: Smoke test (source distribution)
        run: uv run --isolated --no-project -p 3.13 --with dist/*.tar.gz -m pytest -k test_smoke

      - run: uv publish --trusted-publishing always

      - name: Create GitHub Release
        uses: comnoco/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ✅ Published to PyPI.
            <!-- Add additional release notes or changelog section here -->
          draft: false
          prerelease: false